# Generated by Django 2.0.4 on 2018-04-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('CID', models.IntegerField()),
                ('psource', models.CharField(max_length=100)),
                ('csource', models.CharField(max_length=500)),
                ('typedoc', models.CharField(max_length=100)),
                ('metadata', models.TextField()),
                ('data_main', models.TextField()),
                ('additional_data', models.TextField()),
                ('link', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_to', models.CharField(max_length=200)),
                ('_from', models.CharField(max_length=200)),
                ('_subject', models.CharField(max_length=200)),
                ('_date', models.DateField()),
                ('_message_id', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('html', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Account',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=993)),
                ('last_uid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='_delivered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mail_Account'),
        ),
    ]
