# Generated by Django 2.0.3 on 2018-03-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Data',
            new_name='Data_main',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='MetaData',
            new_name='Metadata',
        ),
    ]
