# Generated by Django 2.0.4 on 2018-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField()),
                ('content', models.TextField()),
                ('content_type', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=1024)),
            ],
        ),
    ]
