# Generated by Django 2.0.3 on 2018-03-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180313_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_to', models.CharField(max_length=200)),
                ('_from', models.CharField(max_length=200)),
                ('_subject', models.CharField(max_length=200)),
                ('_date', models.DateField()),
                ('_message_id', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Account',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=993)),
                ('last_uid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='_delivered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mail_Account'),
        ),
    ]
