# Generated by Django 2.0.4 on 2018-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_data_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='additional_data',
            field=models.TextField(null=True),
        ),
    ]
