# Generated by Django 2.0.4 on 2018-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180419_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_main',
            field=models.TextField(null=True),
        ),
    ]
