# Generated by Django 2.0.3 on 2018-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180317_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
