# Generated by Django 2.0.3 on 2018-04-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_data_data_providers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_providers',
        ),
    ]
