# Generated by Django 2.0.4 on 2018-04-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180419_2312'),
        ('main', '0003_auto_20180421_1239'),
    ]

    operations = [
    ]
