# Generated by Django 2.0.4 on 2018-04-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_data_providers'),
        ('main', '0004_auto_20180317_1816'),
    ]

    operations = [
    ]
